server:
  servlet:
    context-path: /api/ranking
  port: 8092

spring:
  application.name: ranking
  datasource:
    url: ${RANKING_DB_URL}
    username: ${RANKING_DB_USERNAME}
    password: ${RANKING_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 1
      maximum-pool-size: 2
# mybatis name rule
mybatis:
  configuration:
    map-underscore-to-camel-case: true
